/*
 * IMPORTANT!
 * This file is generated by grunt tasks during installation, injecting automatically micro apps dependencies.
 * Please do not modify this file manually. To re-build dependencies use `grunt generate--container` task.
 */
(function (root) {
	'use strict';

	function handleStackTrace(error) {
		console.error(error);

		var url = '__logstashUrl__';
		if(url.indexOf('__') === 0) {
			return;
		}
		StackTrace.fromError(error).then(function(stack) {
			StackTrace.report(stack, url, {
				payload: error.message,
				type: error.requireType,
				modules: error.requireModules
			});
		});
	}

	requirejs.onError = function (error) {
		handleStackTrace(error);
	};

	root.handleStackTrace = handleStackTrace;

	require([
		/* deps */
	], function () {
		require([
			'apps/_includes',
			'apps/module'
		], function () {
			angular
				.element(document)
				.ready(function () {
					angular.bootstrap(angular.element('html').addClass('ng-app'), ['app']);
				});
		});
	});
})(window);
