/*
 * IMPORTANT!
 * This file is generated by grunt tasks during installation, injecting automatically micro apps dependencies.
 * Please do not modify this file manually. To re-build dependencies use `grunt generate--container` task.
 */

define([
	// Seed
	'seed/_includes',
	'seed/module',

	// Load config
	'apps/module.conf',

	// Apps
	/* includes */
], function () {
	'use strict';
});
