/*
 * IMPORTANT!
 * This file is generated by grunt tasks during installation, injecting automatically micro apps dependencies.
 * Please do not modify this file manually. To re-build dependencies use `grunt generate--container` task.
 */

/**
 * @namespace app
 */

define(['angular', 'angular-gettext'], function (ng) {
	'use strict';

	var container = ng.module('app', [
		'seed',
		'app.conf',
		/* modules */
	]);

	container.config(function ($cookiesProvider, appConf) {
		_.extend($cookiesProvider, appConf.environmentSettings.cookiesProviderConfig);
	});

	container.run(function ($log, $rootScope) {
		$log = $log.getInstance('app.module');

		$rootScope.appReady = true;

		$log.debug('Set up container configuration');
	});

	return container;
});
